
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-07-13T20:04:05-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "6abe6faff6b035e9334dd05f8c741ae9b7a47440",
 "version": "0.29.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
